# Matrix Manipulation
- numpy arrays act like matries

In [1]:
import numpy as np

X = np.array(
[[73.847017017515, 241.893563180437],
 [68.7819040458903, 162.3104725213],
 [74.1101053917849, 212.7408555565],
 [71.7309784033377, 220.042470303077],
 [69.8817958611153, 206.349800623871],
 [67.2530156878065, 152.212155757083],
 [68.7850812516616, 183.927888604031],
 [68.3485155115879, 167.971110489509],
 [67.018949662883, 175.92944039571],
 [63.4564939783664, 156.399676387112]]
)

In [2]:
X.shape

(10, 2)

## Finding Mean with numpy

In [3]:
# Mean of the first column
np.mean(X[:,0])

69.32138568119487

In [4]:
# Mean of the first five rowa of the second column
np.mean(X[:5,1])

208.667432437037

In [5]:
# Value at ninth row, second column
X[8,1]

175.92944039571

In [6]:
weight = X[:,0] - np.mean(X[:,0])
height = X[:,1] - np.mean(X[:,1])

np.concatenate((weight.reshape((10,1)), height.reshape((10,1))), axis=1)

array([[  4.52563134,  53.9158198 ],
       [ -0.53948164, -25.66727086],
       [  4.78871971,  24.76311217],
       [  2.40959272,  32.06472692],
       [  0.56041018,  18.37205724],
       [ -2.06836999, -35.76558762],
       [ -0.53630443,  -4.04985478],
       [ -0.97287017, -20.00663289],
       [ -2.30243602, -12.04830299],
       [ -5.8648917 , -31.57806699]])

## Adding Matrices with numpy

In [14]:
A = np.array([[1,2],[3,4]])
print(A)

# Add total
print('Total', np.sum(A))

# Add by columns
print('Sum of Columns', np.sum(A, axis=0))

# add by rows
print('Sum of Rows', np.sum(A, axis=1))

[[1 2]
 [3 4]]
Total 10
Sum of Columns [4 6]
Sum of Rows [3 7]


## Matrix, Vector Multiplication

When multiplying an m*n matrix with a vector, we can only multiply it by a vector a size of n*1.

In [7]:
import numpy as np

A = np.array([[1,2],[0,1],[2,3]])
v = np.array([[5],[7]])
print('-Dot product of A and v-')
print(np.dot(A,v))

-Dot product of A and v-
[[19]
 [ 7]
 [31]]


In [12]:
B = np.array([[2, 5],[6, 7]])
print(np.dot(A,B))

[[14 19]
 [ 6  7]
 [22 31]]


### Identity Matrix

In [17]:
B = np.array([[1,0],[0,1]])
print(np.dot(A,B))

[[1 2]
 [0 1]
 [2 3]]


## Can we express linear regression in matrix-vector format?

In [18]:
import numpy as np
import matplotlib.pyplot as plt

# Running Distance in Mile
x = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])

# Water Drinks in Litre
y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])

In [25]:
w1 = 0.25163494 
w0 = 0.79880123 
y_pred = [w1*i + w0 for i in x]
print(y_pred)

[1.629196532, 1.905994966, 2.1827934, 2.4872716774, 2.5426313642, 1.84761565992, 3.25953930826, 2.3544084290800003, 2.7087104245999996, 1.34409414498, 2.57081447748, 3.51419386754, 2.13573766622, 2.81112584518, 2.2215451807599997, 3.1314571237999997, 1.578869544]


### Yes! We can represent linear regression with marties using numpy in two ways

In [28]:
# First
X = np.concatenate((np.transpose([x]), np.ones((len(x), 1))), axis=1)
w = np.array([w1, w0])
print(X)
print(np.dot(X,w))

[[ 3.3    1.   ]
 [ 4.4    1.   ]
 [ 5.5    1.   ]
 [ 6.71   1.   ]
 [ 6.93   1.   ]
 [ 4.168  1.   ]
 [ 9.779  1.   ]
 [ 6.182  1.   ]
 [ 7.59   1.   ]
 [ 2.167  1.   ]
 [ 7.042  1.   ]
 [10.791  1.   ]
 [ 5.313  1.   ]
 [ 7.997  1.   ]
 [ 5.654  1.   ]
 [ 9.27   1.   ]
 [ 3.1    1.   ]]
[1.62919653 1.90599497 2.1827934  2.48727168 2.54263136 1.84761566
 3.25953931 2.35440843 2.70871042 1.34409414 2.57081448 3.51419387
 2.13573767 2.81112585 2.22154518 3.13145712 1.57886954]


In [22]:
# Second
X = np.array([x, np.ones((1, len(x)))])
print(X)
w = np.array([w1, w0])
np.dot(w, X)

[array([ 3.3  ,  4.4  ,  5.5  ,  6.71 ,  6.93 ,  4.168,  9.779,  6.182,
        7.59 ,  2.167,  7.042, 10.791,  5.313,  7.997,  5.654,  9.27 ,
        3.1  ])
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])]


array([[1.62919653, 1.90599497, 2.1827934 , 2.48727168, 2.54263136,
        1.84761566, 3.25953931, 2.35440843, 2.70871042, 1.34409414,
        2.57081448, 3.51419387, 2.13573767, 2.81112585, 2.22154518,
        3.13145712, 1.57886954]])

## Matrix and Vector Transposition

- In linear algebra, the transpose of a matrix is an operator which switches the row and column indices of the matrix by producing another matrix denoted as Aᵀ

### Transposition in numpy

In [35]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print('-------')
print(A.T)
print('-------')
print(np.transpose(A))

[[1 2 3]
 [4 5 6]]
-------
[[1 4]
 [2 5]
 [3 6]]
-------
[[1 4]
 [2 5]
 [3 6]]


## Vector's Norm (distance from origin)

- We have different norm, here we mean L2-norm, which measures the distance of a vector from origin

In [48]:
from numpy import linalg

# What is the norm (distance from origin) of this vector?
v = np.array([3,4])
u = np.array([6,1])

print(linalg.norm(v))
# OR
print(np.sqrt(np.dot(v,v.T)))

5.0
5.0


## How could we find the distance between two vectors?

In [53]:
# By calculating the norm of v - u or the connection of 
print(linalg.norm(u-v))
# OR
print(np.sqrt((linalg.norm(u)**2)+(linalg.norm(v))**2))

4.242640687119285
7.87400787401181
